### ISSUE TITLE
Using SimpleNPC add command create island minecraft closed

### ISSUE THREAD

**Issue by KaptenZee** [BeeAZ-pm-pl/AcidIsland#10]
Helo, i create a NPC to create AcidIsland ac join suddenly minecraft closed! plz help..hope u understand

[Server thread/CRITICAL]: TypeError: "BeeAZ\AcidIsland\commands\subcommand\Join::createIsland(): Argument #1 ($player) must be of type pocketmine\player\Player, pocketmine\console\ConsoleCommandSender given, called in phar:///home/container/plugins/AcidIslandPM.phar/src/BeeAZ/AcidIsland/commands/subcommand/Join.php on line 26" (EXCEPTION) in "plugins/AcidIslandPM.phar/src/BeeAZ/AcidIsland/commands/subcommand/Join" at line 29

**Comment by BeeAZ-pm-pl** [comment]
You created the npc the wrong way !

**Comment by KaptenZee** [comment]
Ops..sorry my bad, ok thanks for reply
