### ISSUE TITLE
Bug i think

### ISSUE THREAD

**Issue by xodamcm** [BeeAZ-pm-pl/AcidIsland#4]
Player can create lots of island I explain me, 
when he do « /ac join » this create island
When player do another ” /ac join” , this doesn’t teleport to the island  like dev 7
This create one island and  another island again and again, players must do /ac tp @s to teleport to them island

**Comment by BeeAZ-pm-pl** [comment]
ok i will fix it

**Comment by BeeAZ-pm-pl** [comment]
Fixed

**Comment by xodamcm** [comment]
Thank you so mutch! To fast for me😁
