### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by xodamcm** [BeeAZ-pm-pl/AcidIsland#5]
Hi 👋, can you please make a combatibility with other plugin like One-Block or Skyblock etc, so just change the name of the world (on creating acid island, this name can’t be playername world, just put ai-playername or maybe ai2-playername) but removing PlayerName for world because we can’t use other plugins cause other plugin use also playername for name of world ..

**Comment by BeeAZ-pm-pl** [comment]
You should use the plugin before creating issues

**Comment by xodamcm** [comment]
I am using the plugin, but when i created an acid island, i am teleported on my skyblock iland

**Comment by BeeAZ-pm-pl** [comment]
You did

**Comment by BeeAZ-pm-pl** [comment]
Have you seen what my world is like? It generates ai-playername
